workerPoolSpecs:
- machineSpec:
    machineType: "${VERTEX_MACHINE_TYPE:-n1-highmem-8}"
    acceleratorType: "${VERTEX_ACCELERATOR_TYPE:-NVIDIA_TESLA_T4}"
    acceleratorCount: ${VERTEX_ACCELERATOR_COUNT:-1}
  replicaCount: ${VERTEX_REPLICA_COUNT:-1}
  containerSpec:
    imageUri: "${VERTEX_IMAGE_URI}"
    command: ["python", "${TRAIN_SCRIPT:-shakespeare.py}"]
    args: ["--train", "--epochs", "${TRAIN_EPOCHS}", "--batch_size", "${TRAIN_BATCH_SIZE}", "--ckpt", "gs://${BUCKET_NAME}/diffusion/checkpoints/${MODEL_NAME:-model}.pth"]
    env:
    - name: "HF_TOKEN"
      value: "${HF_TOKEN}"
baseOutputDirectory:
  outputUriPrefix: "gs://${BUCKET_NAME}/diffusion/outputs"
  
# Checkpoint storage configuration
persistentResourceId: "${VERTEX_PERSISTENT_RESOURCE_ID:-}"
enableWebAccess: false