workerPoolSpecs:
- machineSpec:
    machineType: "n1-standard-4"
    acceleratorType: "NVIDIA_TESLA_T4"
    acceleratorCount: 1
  replicaCount: 1
  containerSpec:
    imageUri: "gcr.io/learnagentspace/text-diffusion:latest"
    command: ["python", "-m", "src.shakespeare"]
    args: ["--sample", "--ckpt", "gs://text-diffusion/diffusion/checkpoints/text-model.pth", "--n", "5"]
baseOutputDirectory:
  outputUriPrefix: "gs://text-diffusion/diffusion/outputs"
enableWebAccess: false